Repository stacks-network/stacks-core, pull requests merged in 2018-03, with the labels that each got.

#766 Expired Names Should Return 404, Not 500
  blockstack/version.py
  blockstack_client/rpc.py
  blockstack_client/version.py
Labels: bug

#768 Subdomain schema response of `/v1/names` should match domain response.
  blockstack/version.py
  blockstack_client/rpc.py
  blockstack_client/version.py
Labels: area/api, kind/bug

#787 snapshot.bsk is a hard link, not a symlink. Compare inode numbers, not link paths
  bin/blockstack-snapshots
Labels: in progress

#788 Increasing the max name length in rpc.py
  blockstack_client/rpc.py
  blockstack_client/version.py
Labels: bug, in progress
