Repository stacks-network/stacks-core, pull requests merged in 2019-06, with the labels that each got.

#991 Implement Response and Option Types
  circle.yml
  sample-programs/names.scm
  sample-programs/tokens.scm
  src/clarity.rs
  src/main.rs
  src/vm/callables.rs
  src/vm/checker/errors.rs
  src/vm/checker/read_only/mod.rs
  src/vm/checker/read_only/tests.rs
  src/vm/checker/typecheck/mod.rs
  src/vm/checker/typecheck/natives/maps.rs
  src/vm/checker/typecheck/natives/mod.rs
  src/vm/checker/typecheck/natives/options.rs
  src/vm/checker/typecheck/tests/contracts.rs
  src/vm/checker/typecheck/tests/mod.rs
  src/vm/contexts.rs
  src/vm/contracts.rs
  src/vm/database/sqlite.rs
  src/vm/docs/mod.rs
  src/vm/errors.rs
  src/vm/functions/database.rs
  src/vm/functions/mod.rs
  src/vm/functions/options.rs
  src/vm/functions/tuples.rs
  src/vm/mod.rs
  src/vm/parser.rs
  src/vm/representations.rs
  src/vm/tests/contracts.rs
  src/vm/tests/datamaps.rs
  src/vm/tests/defines.rs
  src/vm/tests/lists.rs
  src/vm/tests/simple_apply_eval.rs
  src/vm/types.rs
Labels: clarity

#1006 Fixing change which broke the documentation generation
  src/vm/docs/mod.rs
Labels: clarity

#1010 `eq?` type enforcement
  src/vm/checker/read_only/tests.rs
  src/vm/checker/typecheck/mod.rs
  src/vm/checker/typecheck/natives/mod.rs
  src/vm/checker/typecheck/natives/options.rs
  src/vm/checker/typecheck/tests/contracts.rs
  src/vm/checker/typecheck/tests/mod.rs
  src/vm/functions/mod.rs
  src/vm/types.rs
Labels: clarity, enhancement

#1009 Add random address generation
  src/clarity.rs
Labels: clarity, feature

#1007 Easing tuple construction for fetch-entry / set-entry / delete-entry / add-entry
  src/vm/checker/read_only/mod.rs
  src/vm/checker/read_only/tests.rs
  src/vm/checker/typecheck/natives/maps.rs
  src/vm/checker/typecheck/natives/mod.rs
  src/vm/checker/typecheck/tests/mod.rs
  src/vm/docs/mod.rs
  src/vm/functions/database.rs
  src/vm/functions/mod.rs
  src/vm/functions/tuples.rs
  src/vm/tests/datamaps.rs
Labels: clarity

#1004 Implement `(filter ...)` and improved list types
  .gitignore
  sip/sip-002-smart-contract-language.md
  src/vm/checker/read_only/mod.rs
  src/vm/checker/typecheck/natives/lists.rs
  src/vm/checker/typecheck/natives/mod.rs
  src/vm/checker/typecheck/tests/contracts.rs
  src/vm/checker/typecheck/tests/mod.rs
  src/vm/docs/mod.rs
  src/vm/functions/lists.rs
  src/vm/functions/mod.rs
  src/vm/tests/lists.rs
  src/vm/types.rs
Labels: clarity

#1017 Add `defines` to vm::docs
  src/vm/docs/mod.rs
Labels: clarity

#1025 Classifying Interpreter Errors
  src/vm/callables.rs
  src/vm/checker/errors.rs
  src/vm/checker/typecheck/mod.rs
  src/vm/checker/typecheck/natives/mod.rs
  src/vm/checker/typecheck/tests/mod.rs
  src/vm/contexts.rs
  src/vm/contracts.rs
  src/vm/database/sqlite.rs
  src/vm/docs/mod.rs
  src/vm/errors.rs
  src/vm/functions/arithmetic.rs
  src/vm/functions/boolean.rs
  src/vm/functions/database.rs
  src/vm/functions/define.rs
  src/vm/functions/lists.rs
  src/vm/functions/mod.rs
  src/vm/functions/options.rs
  src/vm/functions/tuples.rs
  src/vm/mod.rs
  src/vm/parser.rs
  src/vm/tests/contracts.rs
  src/vm/tests/datamaps.rs
  src/vm/tests/defines.rs
  src/vm/tests/lists.rs
  src/vm/tests/simple_apply_eval.rs
  src/vm/types.rs
  src/vm/variables.rs
Labels: clarity

#1018 Friendlier panics
  circle.yml
  src/clarity.rs
Labels: clarity

#1022 Introducing persisted variables
  src/vm/checker/errors.rs
  src/vm/checker/read_only/mod.rs
  src/vm/checker/typecheck/contexts.rs
  src/vm/checker/typecheck/mod.rs
  src/vm/checker/typecheck/natives/mod.rs
  src/vm/checker/typecheck/tests/mod.rs
  src/vm/database/sqlite.rs
  src/vm/docs/mod.rs
  src/vm/errors.rs
  src/vm/functions/database.rs
  src/vm/functions/define.rs
  src/vm/functions/mod.rs
  src/vm/mod.rs
  src/vm/tests/datamaps.rs
  src/vm/types.rs
  src/vm/variables.rs
Labels: clarity

#1026 Update SIP-002 with latest syntax
  sip/sip-002-smart-contract-language.md
Labels: clarity
