Repository stacks-network/stacks-core, pull requests merged in 2020-07, with the labels that each got.

#1711 fix rewards values, addresses #1710
  src/chainstate/stacks/db/blocks.rs
  src/chainstate/stacks/miner.rs
Labels: consensus-critical

#1731 Nicer RPC deserialization errors
  src/net/connection.rs
  src/net/http.rs
  src/net/mod.rs
  src/net/rpc.rs
  testnet/stacks-node/src/tests/integrations.rs
Labels: enhancement

#1769 Add workflow for bitcoind integration tests
  .github/actions/bitcoin-int-tests/Dockerfile.bitcoin-tests
  .github/workflows/bitcoin-tests.yml
  .github/workflows/deploy.yml
  circle.yml
  testnet/stacks-node/src/keychain.rs
  testnet/stacks-node/src/tests/bitcoin_regtest.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
Labels: test

#1743 Stacks chainstate refactor for PoX
  src/burnchains/burnchain.rs
  src/chainstate/burn/db/sortdb.rs
  src/chainstate/burn/mod.rs
  src/chainstate/burn/operations/leader_block_commit.rs
  src/chainstate/burn/operations/leader_key_register.rs
  src/chainstate/burn/operations/user_burn_support.rs
  src/chainstate/burn/sortition.rs
  src/chainstate/stacks/block.rs
  src/chainstate/stacks/db/accounts.rs
  src/chainstate/stacks/db/blocks.rs
  src/chainstate/stacks/db/headers.rs
  src/chainstate/stacks/db/mod.rs
  src/chainstate/stacks/db/transactions.rs
  src/chainstate/stacks/db/unconfirmed.rs
  src/chainstate/stacks/miner.rs
  src/chainstate/stacks/mod.rs
  src/core/mempool.rs
  src/core/mod.rs
  src/main.rs
  src/net/codec.rs
  src/net/download.rs
  src/net/inv.rs
  src/net/mod.rs
  src/net/p2p.rs
  src/net/relay.rs
  src/net/rpc.rs
  src/net/server.rs
  src/vm/database/clarity_db.rs
  src/vm/docs/mod.rs
  src/vm/variables.rs
  testnet/stacks-node/src/neon_node.rs
  testnet/stacks-node/src/node.rs
  testnet/stacks-node/src/run_loop/helium.rs
  testnet/stacks-node/src/tests/bitcoin_regtest.rs
  testnet/stacks-node/src/tests/integrations.rs
  testnet/stacks-node/src/tests/mempool.rs
  testnet/stacks-node/src/tests/mod.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
Labels: consensus-critical

#1770 implement withdraw-reward
  src/chainstate/stacks/db/blocks.rs
  src/chainstate/stacks/db/mod.rs
  src/chainstate/stacks/miner.rs
Labels: consensus-critical
