Repository stacks-network/stacks-core, pull requests merged in 2022-08, with the labels that each got.

#3192 Feat/explicit-contract-version
  .github/actions/bitcoin-int-tests/Dockerfile.code-cov
  clarity/src/vm/analysis/analysis_db.rs
  clarity/src/vm/clarity.rs
  clarity/src/vm/contexts.rs
  clarity/src/vm/docs/mod.rs
  clarity/src/vm/test_util/mod.rs
  clarity/src/vm/tests/assets.rs
  clarity/src/vm/tests/contracts.rs
  clarity/src/vm/tests/simple_apply_eval.rs
  clarity/src/vm/tests/traits.rs
  src/chainstate/coordinator/tests.rs
  src/chainstate/stacks/block.rs
  src/chainstate/stacks/boot/contract_tests.rs
  src/chainstate/stacks/boot/mod.rs
  src/chainstate/stacks/db/blocks.rs
  src/chainstate/stacks/db/mod.rs
  src/chainstate/stacks/db/transactions.rs
  src/chainstate/stacks/miner.rs
  src/chainstate/stacks/mod.rs
  src/chainstate/stacks/tests/accounting.rs
  src/chainstate/stacks/tests/block_construction.rs
  src/chainstate/stacks/tests/mod.rs
  src/chainstate/stacks/transaction.rs
  src/clarity_cli.rs
  src/clarity_vm/clarity.rs
  src/clarity_vm/tests/analysis_costs.rs
  src/clarity_vm/tests/contracts.rs
  src/clarity_vm/tests/costs.rs
  src/clarity_vm/tests/events.rs
  src/clarity_vm/tests/forking.rs
  src/clarity_vm/tests/large_contract.rs
  src/cost_estimates/fee_medians.rs
  src/cost_estimates/fee_scalar.rs
  src/cost_estimates/pessimistic.rs
  src/net/download.rs
  src/net/mod.rs
  src/net/relay.rs
  src/net/rpc.rs
  src/net/server.rs
  testnet/stacks-node/src/run_loop/mod.rs
  testnet/stacks-node/src/tests/epoch_205.rs
  testnet/stacks-node/src/tests/mod.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
Labels: stacks-2.1

#3228 Fix/3227
  CHANGELOG.md
  src/net/atlas/download.rs
  src/net/download.rs
  src/net/inv.rs
  src/net/p2p.rs
  src/net/relay.rs
  src/net/server.rs
  testnet/stacks-node/src/neon_node.rs
Labels: 2.05.0.3.0

#3212 Feat/drop problematic transactions
  src/chainstate/stacks/db/blocks.rs
  src/chainstate/stacks/db/transactions.rs
  src/chainstate/stacks/miner.rs
  src/chainstate/stacks/mod.rs
  src/core/mempool.rs
  src/core/tests/mod.rs
  src/net/p2p.rs
Labels: 2.05.0.3.0

#3219 Adds human-readable time to logger
  CHANGELOG.md
  stacks-common/src/util/log.rs
Labels: 2.05.0.3.0

#3236 Fix/3216
  CHANGELOG.md
  testnet/stacks-node/src/neon_node.rs
  testnet/stacks-node/src/run_loop/neon.rs
Labels: 2.05.0.3.0

#3234 Feat/runtime analysis errors
  src/chainstate/stacks/db/blocks.rs
  src/chainstate/stacks/db/transactions.rs
  src/chainstate/stacks/events.rs
Labels: stacks-2.1

#3233 Feat/bill-tx-fee-before-processing
  src/chainstate/stacks/db/blocks.rs
  src/chainstate/stacks/db/transactions.rs
  src/chainstate/stacks/events.rs
Labels: stacks-2.1

#3200 Move puppet-chain to contrib/tools
  .cargo/config
  .gitignore
  .vscode/launch.json
  Cargo.lock
  Cargo.toml
  Dockerfile
  Dockerfile.stretch
  contrib/tools/puppet-chain/.dockerignore
  contrib/tools/puppet-chain/Cargo.lock
  contrib/tools/puppet-chain/Cargo.toml
  contrib/tools/puppet-chain/Dockerfile
  contrib/tools/puppet-chain/README.md
  contrib/tools/puppet-chain/config.toml.default
  contrib/tools/puppet-chain/local-leader.toml.default
  contrib/tools/puppet-chain/src/main.rs
Labels: chore, 2.05.0.3.0

#3235 Add mock-miner config file
  README.md
  testnet/stacks-node/conf/mainnet-mockminer-conf.toml
Labels: 2.05.0.3.0

#3255 Update CHANGELOG for 2.05.0.3.0
  CHANGELOG.md
Labels: 2.05.0.3.0

#3245 Feat/get pox addrs
  .github/workflows/bitcoin-tests.yml
  clarity/src/vm/database/clarity_db.rs
  clarity/src/vm/docs/mod.rs
  clarity/src/vm/functions/database.rs
  clarity/src/vm/test_util/mod.rs
  clarity/src/vm/types/mod.rs
  src/burnchains/burnchain.rs
  src/burnchains/db.rs
  src/burnchains/mod.rs
  src/chainstate/burn/db/mod.rs
  src/chainstate/burn/db/processing.rs
  src/chainstate/burn/db/sortdb.rs
  src/chainstate/burn/operations/leader_block_commit.rs
  src/chainstate/burn/operations/leader_key_register.rs
  src/chainstate/burn/operations/mod.rs
  src/chainstate/burn/operations/stack_stx.rs
  src/chainstate/burn/operations/transfer_stx.rs
  src/chainstate/burn/operations/user_burn_support.rs
  src/chainstate/coordinator/mod.rs
  src/chainstate/coordinator/tests.rs
  src/chainstate/stacks/address.rs
  src/chainstate/stacks/boot/contract_tests.rs
  src/chainstate/stacks/boot/mod.rs
  src/chainstate/stacks/boot/pox_2_tests.rs
  src/chainstate/stacks/db/blocks.rs
  src/chainstate/stacks/db/transactions.rs
  src/clarity_vm/clarity.rs
  src/clarity_vm/database/mod.rs
  src/net/mod.rs
  src/util_lib/db.rs
  stacks-common/src/address/mod.rs
  testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
  testnet/stacks-node/src/event_dispatcher.rs
  testnet/stacks-node/src/neon_node.rs
  testnet/stacks-node/src/node.rs
  testnet/stacks-node/src/tests/epoch_205.rs
  testnet/stacks-node/src/tests/epoch_21.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
Labels: stacks-2.1

#3254 Cache Lex Matchers
  clarity/src/vm/ast/parser/mod.rs
Labels: 2.05.0.3.0
