Repository stacks-network/stacks-core, pull requests merged in 2023-12, with the labels that each got.

#4114 Feat/tenure change validation
  Cargo.lock
  stacks-common/src/types/chainstate.rs
  stacks-common/src/util/macros.rs
  stacks-common/src/util/secp256k1.rs
  stackslib/src/burnchains/tests/mod.rs
  stackslib/src/chainstate/burn/db/sortdb.rs
  stackslib/src/chainstate/nakamoto/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/miner.rs
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/nakamoto/tenure.rs
  stackslib/src/chainstate/nakamoto/tests/mod.rs
  stackslib/src/chainstate/nakamoto/tests/node.rs
  stackslib/src/chainstate/stacks/block.rs
  stackslib/src/chainstate/stacks/db/mod.rs
  stackslib/src/chainstate/stacks/db/transactions.rs
  stackslib/src/chainstate/stacks/miner.rs
  stackslib/src/chainstate/stacks/mod.rs
  stackslib/src/chainstate/stacks/tests/mod.rs
  stackslib/src/chainstate/stacks/transaction.rs
  stackslib/src/net/relay.rs
  testnet/stacks-node/src/mockamoto.rs
  testnet/stacks-node/src/mockamoto/signer.rs
Labels: neon3.0

#4161 use pull_request to trigger ci runs
  .github/workflows/ci.yml
Labels: bug, CI

#4162 use pull_request to trigger ci runs
  .github/workflows/ci.yml
Labels: bug, CI

#4133 Nakamoto-Neon: Add nakamoto_node
  .github/workflows/bitcoin-tests.yml
  Cargo.lock
  Cargo.toml
  stackslib/src/burnchains/bitcoin/indexer.rs
  stackslib/src/chainstate/nakamoto/coordinator/mod.rs
  stackslib/src/chainstate/nakamoto/miner.rs
  stackslib/src/chainstate/stacks/miner.rs
  stackslib/src/core/mod.rs
  testnet/stacks-node/Cargo.toml
  testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
  testnet/stacks-node/src/config.rs
  testnet/stacks-node/src/globals.rs
  testnet/stacks-node/src/keychain.rs
  testnet/stacks-node/src/main.rs
  testnet/stacks-node/src/mockamoto.rs
  testnet/stacks-node/src/mockamoto/signer.rs
  testnet/stacks-node/src/mockamoto/tests.rs
  testnet/stacks-node/src/nakamoto_node.rs
  testnet/stacks-node/src/nakamoto_node/miner.rs
  testnet/stacks-node/src/nakamoto_node/peer.rs
  testnet/stacks-node/src/nakamoto_node/relayer.rs
  testnet/stacks-node/src/neon_node.rs
  testnet/stacks-node/src/run_loop/boot_nakamoto.rs
  testnet/stacks-node/src/run_loop/mod.rs
  testnet/stacks-node/src/run_loop/nakamoto.rs
  testnet/stacks-node/src/run_loop/neon.rs
  testnet/stacks-node/src/tests/bitcoin_regtest.rs
  testnet/stacks-node/src/tests/mod.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
Labels: neon3.0

#4160 use pull_request to trigger ci runs
  .github/workflows/ci.yml
Labels: bug, CI

#4163 pox-4: remove pox-reject
  stackslib/src/chainstate/stacks/boot/docs.rs
  stackslib/src/chainstate/stacks/boot/mod.rs
  stackslib/src/chainstate/stacks/boot/pox-4.clar
  stackslib/src/clarity_vm/clarity.rs
  stackslib/src/net/api/getpoxinfo.rs
  testnet/stacks-node/src/mockamoto/tests.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
Labels: nakamoto
