Repository stacks-network/stacks-core, pull requests merged in 2023-08, with the labels that each got.

#3774 Fix: Parsing of config mixes connect_timeout and handshake_timeout
  testnet/stacks-node/src/config.rs
Labels: bug

#3552 Feat/stackerdb discovery
  stackslib/src/burnchains/bitcoin/indexer.rs
  stackslib/src/chainstate/coordinator/mod.rs
  stackslib/src/main.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/connection.rs
  stackslib/src/net/db.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/neighbors.rs
  stackslib/src/net/neighbors/comms.rs
  stackslib/src/net/neighbors/db.rs
  stackslib/src/net/neighbors/mod.rs
  stackslib/src/net/neighbors/neighbor.rs
  stackslib/src/net/neighbors/walk.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/prune.rs
  stackslib/src/net/rpc.rs
  stackslib/src/net/tests/mod.rs
  stackslib/src/net/tests/neighbors.rs
  stackslib/src/util_lib/db.rs
  testnet/stacks-node/src/neon_node.rs
  testnet/stacks-node/src/node.rs
Labels: frozen, sbtc

#3558 Feat/stackerdb chunk db
  stackslib/src/net/codec.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/stackerdb/bits.rs
  stackslib/src/net/stackerdb/db.rs
  stackslib/src/net/stackerdb/mod.rs
  stackslib/src/net/stackerdb/tests/bits.rs
  stackslib/src/net/stackerdb/tests/db.rs
  stackslib/src/net/stackerdb/tests/mod.rs
  stackslib/src/util_lib/db.rs
Labels: sbtc

#3560 Feat/stackerdb sync
  stackslib/src/net/chat.rs
  stackslib/src/net/codec.rs
  stackslib/src/net/connection.rs
  stackslib/src/net/db.rs
  stackslib/src/net/inv.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/neighbors/comms.rs
  stackslib/src/net/neighbors/walk.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/poll.rs
  stackslib/src/net/relay.rs
  stackslib/src/net/stackerdb/db.rs
  stackslib/src/net/stackerdb/mod.rs
  stackslib/src/net/stackerdb/sync.rs
  stackslib/src/net/stackerdb/tests/bits.rs
  stackslib/src/net/stackerdb/tests/db.rs
  stackslib/src/net/stackerdb/tests/mod.rs
  stackslib/src/net/stackerdb/tests/sync.rs
  testnet/stacks-node/src/config.rs
  testnet/stacks-node/src/neon_node.rs
  testnet/stacks-node/src/node.rs
Labels: sbtc
