Repository stacks-network/stacks-core, pull requests merged in 2024-02, with the labels that each got.

#4232 Nakamoto Tenure Inventories
  stackslib/src/chainstate/burn/mod.rs
  stackslib/src/chainstate/burn/operations/leader_block_commit.rs
  stackslib/src/chainstate/nakamoto/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/tenure.rs
  stackslib/src/chainstate/nakamoto/tests/node.rs
  stackslib/src/chainstate/stacks/db/transactions.rs
  stackslib/src/chainstate/stacks/mod.rs
  stackslib/src/net/api/tests/liststackerdbreplicas.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/codec.rs
  stackslib/src/net/download.rs
  stackslib/src/net/inv/epoch2x.rs
  stackslib/src/net/inv/mod.rs
  stackslib/src/net/inv/nakamoto.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/relay.rs
  stackslib/src/net/tests/inv/epoch2x.rs
  stackslib/src/net/tests/inv/mod.rs
  stackslib/src/net/tests/inv/nakamoto.rs
  stackslib/src/net/tests/mod.rs
Labels: argon3.0

#4345 Hotfix/stackerdb stale view
  stackslib/src/chainstate/burn/db/sortdb.rs
  stackslib/src/net/api/poststackerdbchunk.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/stackerdb/mod.rs
  stackslib/src/net/stackerdb/sync.rs
  stackslib/src/net/stackerdb/tests/sync.rs
  testnet/stacks-node/src/node.rs
Labels: stacker-db

#4374 [CI] fix error in release step that generates checksums
  .github/workflows/github-release.yml
Labels: release-blocking, CI

#4381 Update wsts workspace dependency to v8.1
  Cargo.lock
  Cargo.toml
Labels: chore, argon3.0

#4409 Fix: only report codecov status after ci
  codecov.yml
Labels: enhancement

#4384 Move Checksum Generation to Composite
  .github/workflows/github-release.yml
Labels: enhancement, CI

#4380 Mutants Optimisations: big-packages, timeout multiplier, stacks-signer case
  .github/workflows/pr-differences-mutants.yml
Labels: testing

#4438 Update ci trigger to enable merge queue in next
  .github/workflows/ci.yml
Labels: enhancement, CI

#4401 Check Multiple Tests' Success at Once
  .github/workflows/atlas-tests.yml
  .github/workflows/bitcoin-tests.yml
  .github/workflows/epoch-tests.yml
  .github/workflows/slow-tests.yml
  .github/workflows/stacks-core-tests.yml
  docs/ci-release.md
Labels: enhancement, CI
