Repository stacks-network/stacks-core, pull requests merged in 2024-04, with the labels that each got.

#4606 Migrate Epoch 2.4 chainstate to Epoch 2.5 without a genesis sync
  stackslib/src/burnchains/burnchain.rs
  stackslib/src/chainstate/burn/db/sortdb.rs
  stackslib/src/chainstate/burn/operations/leader_block_commit.rs
  stackslib/src/chainstate/coordinator/mod.rs
  stackslib/src/chainstate/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/coordinator/mod.rs
  stackslib/src/chainstate/nakamoto/coordinator/tests.rs
  stackslib/src/clarity_vm/tests/epoch_switch.rs
  stackslib/src/main.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/tests/mod.rs
  testnet/stacks-node/src/burnchains/mocknet_controller.rs
  testnet/stacks-node/src/run_loop/neon.rs
Labels: xenon

#4646 remove portable flag
  .cargo/config
  .github/actions/dockerfiles/Dockerfile.debian-source
  Dockerfile
  Dockerfile.debian
  README.md
  stacks-signer/Cargo.toml
  testnet/stacks-node/Cargo.toml
Labels: CI

#4664 Chore/remove portable
  .cargo/config
  .github/actions/dockerfiles/Dockerfile.debian-source
  Dockerfile
  Dockerfile.debian
  README.md
  stacks-signer/Cargo.toml
  testnet/stacks-node/Cargo.toml
Labels: CI, 2.5

#4667 Feat: add affirmation map overrides to xenon default config for epoch 2.5
  stackslib/src/core/mod.rs
  testnet/stacks-node/src/config.rs
Labels: 2.5

#4671 update release workflow to tag the correct commit
  .github/workflows/github-release.yml
Labels: bug, CI, 2.5

#4682 Add missing stacks-signer binary to release docker images
  .github/actions/dockerfiles/Dockerfile.alpine-binary
  .github/actions/dockerfiles/Dockerfile.debian-binary
Labels: 2.5, 2.5-signer-binary

#4550 [pox-4] Pool Stacking stateful property-based tests
  contrib/core-contract-tests/package-lock.json
  contrib/core-contract-tests/package.json
  contrib/core-contract-tests/tests/pox-4/pox-4.stateful-prop.test.ts
  contrib/core-contract-tests/tests/pox-4/pox_AllowContractCallerCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_CommandModel.ts
  contrib/core-contract-tests/tests/pox-4/pox_Commands.ts
  contrib/core-contract-tests/tests/pox-4/pox_DelegateStackExtendCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_DelegateStackIncreaseCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_DelegateStackStxCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_DelegateStxCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_DisallowContractCallerCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_GetStackingMinimumCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_GetStxAccountCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_RevokeDelegateStxCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_StackAggregationCommitAuthCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_StackAggregationCommitIndexedAuthCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_StackAggregationCommitIndexedSigCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_StackAggregationCommitSigCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_StackAggregationIncreaseCommand.ts
  contrib/core-contract-tests/tests/pox-4/pox_StackStxCommand.ts
Labels: stateful-testing
