Repository stacks-network/stacks-core, pull requests merged in 2024-08, with the labels that each got.

#5058 CI - Remove Unit Tests From Check
  .github/workflows/stacks-core-tests.yml
Labels: enhancement, CI

#5057 docs & script for running cargo mutants locally on CI limitation
  contrib/tools/local-mutation-testing.sh
  docs/mutation-testing.md
Labels: mutation-testing, 3.0-Testing

#5082 CI Mutants: add workfow dispatch for GUI
  .github/workflows/pr-differences-mutants.yml
Labels: mutation-testing

#5083 CI Mutants: Action Membership Run
  .github/workflows/pr-differences-mutants.yml
Labels: mutation-testing, 3.0-Testing
