Repository stacks-network/stacks-core, pull requests merged in 2024-05, with the labels that each got.

#4743 Feat/mock mining hot swap
  testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
  testnet/stacks-node/src/config.rs
  testnet/stacks-node/src/nakamoto_node.rs
  testnet/stacks-node/src/nakamoto_node/miner.rs
  testnet/stacks-node/src/neon_node.rs
  testnet/stacks-node/src/run_loop/nakamoto.rs
  testnet/stacks-node/src/run_loop/neon.rs
Labels: 3.0, 3.0-must, 3.0-Miner

#4766 [CI] 4746 - Avoid extraneous CI runs (master)
  .github/workflows/ci.yml
Labels: CI

#4764 [CI] 4746 - Avoid extraneous CI runs (next)
  .github/workflows/ci.yml
Labels: CI

#4765 [CI] 4746 - Avoid extraneous CI runs (develop)
  .github/workflows/ci.yml
Labels: CI

#4544 Add CODEOWNERS
  CODEOWNERS
Labels: enhancement, security

#4792 CI: Update Used Actions' Versions
  .github/workflows/ci.yml
  .github/workflows/clarity-js-sdk-pr.yml
  .github/workflows/docs-pr.yml
  .github/workflows/github-release.yml
  .github/workflows/image-build-binary.yml
  .github/workflows/image-build-source.yml
  .github/workflows/stacks-core-tests.yml
Labels: enhancement, CI

#4797 Signer message for reward set not determined or not registered signer
  stacks-signer/src/runloop.rs
Labels: nakamoto, 3.0-Signer

#4800 Use debug logging for connection issues of private IPs
  stackslib/src/net/neighbors/walk.rs
  stackslib/src/net/stackerdb/sync.rs
Labels: 3.0, 3.0-must

#4782 warn for not using local stacks node with the signer
  stacks-signer/src/v1/mod.rs
Labels: nakamoto

#4821 Fix/StackerDB Audit
  stackslib/src/net/mod.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/stackerdb/config.rs
  stackslib/src/net/stackerdb/mod.rs
  stackslib/src/net/stackerdb/tests/config.rs
  testnet/stacks-node/src/neon_node.rs
Labels: nakamoto, 3.0-must
