Repository stacks-network/stacks-core, pull requests merged in 2024-07, with the labels that each got.

#4918 Add skip header for timeout mutants - pr #4877 related
  stackslib/src/net/unsolicited.rs
Labels: mutation-testing

#4930 MARF'ed Nakamoto chainstate
  clarity/src/vm/database/clarity_db.rs
  clarity/src/vm/docs/mod.rs
  clarity/src/vm/test_util/mod.rs
  stacks-common/src/libcommon.rs
  stacks-common/src/types/mod.rs
  stackslib/src/chainstate/burn/db/sortdb.rs
  stackslib/src/chainstate/coordinator/mod.rs
  stackslib/src/chainstate/nakamoto/coordinator/mod.rs
  stackslib/src/chainstate/nakamoto/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/keys.rs
  stackslib/src/chainstate/nakamoto/miner.rs
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/nakamoto/signer_set.rs
  stackslib/src/chainstate/nakamoto/staging_blocks.rs
  stackslib/src/chainstate/nakamoto/tenure.rs
  stackslib/src/chainstate/nakamoto/tests/mod.rs
  stackslib/src/chainstate/nakamoto/tests/node.rs
  stackslib/src/chainstate/stacks/boot/mod.rs
  stackslib/src/chainstate/stacks/boot/pox_2_tests.rs
  stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
  stackslib/src/chainstate/stacks/boot/signers_voting_tests.rs
  stackslib/src/chainstate/stacks/db/accounts.rs
  stackslib/src/chainstate/stacks/db/mod.rs
  stackslib/src/chainstate/stacks/db/unconfirmed.rs
  stackslib/src/chainstate/stacks/mod.rs
  stackslib/src/chainstate/stacks/tests/mod.rs
  stackslib/src/clarity_vm/database/mod.rs
  stackslib/src/core/mempool.rs
  stackslib/src/core/mod.rs
  stackslib/src/net/api/get_tenures_fork_info.rs
  stackslib/src/net/api/getinfo.rs
  stackslib/src/net/api/gettenureinfo.rs
  stackslib/src/net/api/postblock_v3.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/download/nakamoto/download_state_machine.rs
  stackslib/src/net/download/nakamoto/mod.rs
  stackslib/src/net/download/nakamoto/tenure.rs
  stackslib/src/net/download/nakamoto/tenure_downloader.rs
  stackslib/src/net/download/nakamoto/tenure_downloader_set.rs
  stackslib/src/net/download/nakamoto/tenure_downloader_unconfirmed.rs
  stackslib/src/net/httpcore.rs
  stackslib/src/net/inv/nakamoto.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/neighbors/rpc.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/relay.rs
  stackslib/src/net/tests/download/nakamoto.rs
  stackslib/src/net/tests/inv/nakamoto.rs
  stackslib/src/net/tests/mod.rs
  stackslib/src/net/tests/relay/epoch2x.rs
  stackslib/src/net/unsolicited.rs
  stackslib/src/util_lib/db.rs
  testnet/stacks-node/src/nakamoto_node/miner.rs
  testnet/stacks-node/src/nakamoto_node/relayer.rs
  testnet/stacks-node/src/node.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
Labels: 3.0-must

#4966 Nakamoto mempool sync
  stackslib/src/chainstate/stacks/miner.rs
  stackslib/src/chainstate/stacks/tests/block_construction.rs
  stackslib/src/core/mempool.rs
  stackslib/src/core/tests/mod.rs
  stackslib/src/net/api/postmempoolquery.rs
  stackslib/src/net/api/tests/mod.rs
  stackslib/src/net/api/tests/postmempoolquery.rs
  stackslib/src/net/mempool/mod.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/rpc.rs
  stackslib/src/net/tests/inv/nakamoto.rs
  stackslib/src/net/tests/mempool/mod.rs
  stackslib/src/net/tests/mod.rs
Labels: 3.0, 3.0-Testing

#4968 Modify Workflow to Build Signer Releases
  .github/actions/dockerfiles/Dockerfile.alpine-binary
  .github/actions/dockerfiles/Dockerfile.debian-binary
  .github/workflows/ci.yml
  .github/workflows/github-release.yml
  .github/workflows/image-build-binary.yml
  docs/release-process.md
  stacks-signer/CHANGELOG.md
  stacks-signer/release-process.md
Labels: enhancement, CI

#5016 Oneliner to set signer version at compile time with STACKS_NODE_VERSION
  stacks-signer/src/cli.rs
Labels: 3.0-Signer

#5014 Chore/move signer logs to info
  stacks-signer/src/runloop.rs
  stacks-signer/src/v0/signer.rs
  stacks-signer/src/v1/signer.rs
Labels: 3.0-Testing
