Repository stacks-network/stacks-core, pull requests merged in 2024-09, with the labels that each got.

#5100 CI Mutants: Action Membership Run Updated to match Develop branch
  .github/workflows/pr-differences-mutants.yml
Labels: mutation-testing

#5156 Adds Test - Non standard transaction, but not invalid being anchored
  stackslib/src/chainstate/stacks/tests/block_construction.rs
Labels: 3.0-must, 3.0-Testing

#5163 Check if we are the sortition winner before attempting to mock sign
  .github/workflows/bitcoin-tests.yml
  testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
  testnet/stacks-node/src/neon_node.rs
  testnet/stacks-node/src/tests/signer/v0.rs
Labels: 3.0-must

#5075 Test partial tenure fork
  .github/workflows/bitcoin-tests.yml
  stackslib/src/chainstate/nakamoto/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/net/relay.rs
  testnet/stacks-node/src/nakamoto_node/miner.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
  testnet/stacks-node/src/tests/signer/v0.rs
Labels: 3.0-must

#5093 Feat/more multi miner fixes jude
  .github/workflows/bitcoin-tests.yml
  libstackerdb/src/libstackerdb.rs
  stackslib/src/burnchains/db.rs
  stackslib/src/chainstate/burn/db/processing.rs
  stackslib/src/chainstate/burn/db/sortdb.rs
  stackslib/src/chainstate/coordinator/mod.rs
  stackslib/src/chainstate/nakamoto/coordinator/mod.rs
  stackslib/src/chainstate/nakamoto/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/nakamoto/tests/node.rs
  stackslib/src/chainstate/stacks/db/mod.rs
  stackslib/src/net/api/postblock.rs
  stackslib/src/net/api/postblock_v3.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/connection.rs
  stackslib/src/net/download/nakamoto/download_state_machine.rs
  stackslib/src/net/download/nakamoto/mod.rs
  stackslib/src/net/download/nakamoto/tenure.rs
  stackslib/src/net/download/nakamoto/tenure_downloader.rs
  stackslib/src/net/download/nakamoto/tenure_downloader_unconfirmed.rs
  stackslib/src/net/inv/nakamoto.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/neighbors/db.rs
  stackslib/src/net/neighbors/mod.rs
  stackslib/src/net/neighbors/walk.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/relay.rs
  stackslib/src/net/rpc.rs
  stackslib/src/net/stackerdb/mod.rs
  stackslib/src/net/stackerdb/sync.rs
  stackslib/src/net/stackerdb/tests/sync.rs
  stackslib/src/net/tests/download/nakamoto.rs
  stackslib/src/net/tests/mod.rs
  stackslib/src/net/tests/relay/epoch2x.rs
  stackslib/src/net/tests/relay/nakamoto.rs
  stackslib/src/net/unsolicited.rs
  testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
  testnet/stacks-node/src/config.rs
  testnet/stacks-node/src/nakamoto_node/miner.rs
  testnet/stacks-node/src/nakamoto_node/relayer.rs
  testnet/stacks-node/src/run_loop/nakamoto.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
Labels: 3.0-must

#5173 Fix/signer block state machine
  stacks-signer/src/client/stacks_client.rs
  stacks-signer/src/runloop.rs
  stacks-signer/src/signerdb.rs
  stacks-signer/src/v0/signer.rs
Labels: 3.0-must

#5137 fix: Improve DB deadlock detection/logging
  clarity/src/vm/database/sqlite.rs
  stacks-common/src/util/db.rs
  stacks-common/src/util/mod.rs
  stackslib/src/util_lib/db.rs
Labels: 3.0-must

#5175 chore: add info to signature gathering failure logs
  testnet/stacks-node/src/nakamoto_node/miner.rs
Labels: 3.0-must

#5164 HOTFIX: Check if we are the sortition winner before attempting to mock sign
  .github/workflows/bitcoin-tests.yml
  stackslib/src/net/stackerdb/mod.rs
  stackslib/src/net/stackerdb/sync.rs
  testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
  testnet/stacks-node/src/neon_node.rs
  testnet/stacks-node/src/tests/signer/v0.rs
Labels: 3.0-must

#5138 Fix/5136 node and miner
  .github/workflows/bitcoin-tests.yml
  libsigner/src/events.rs
  libsigner/src/v0/messages.rs
  stacks-common/src/bitvec.rs
  stacks-signer/Cargo.toml
  stacks-signer/src/chainstate.rs
  stacks-signer/src/client/mod.rs
  stacks-signer/src/client/stackerdb.rs
  stacks-signer/src/client/stacks_client.rs
  stacks-signer/src/config.rs
  stacks-signer/src/lib.rs
  stacks-signer/src/runloop.rs
  stacks-signer/src/signerdb.rs
  stacks-signer/src/tests/chainstate.rs
  stacks-signer/src/v0/signer.rs
  stacks-signer/src/v1/signer.rs
  stackslib/src/chainstate/burn/db/sortdb.rs
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/stacks/db/mod.rs
  stackslib/src/chainstate/stacks/miner.rs
  stackslib/src/net/api/gettenuretip.rs
  stackslib/src/net/api/mod.rs
  stackslib/src/net/api/postblock_proposal.rs
  stackslib/src/net/api/tests/gettenuretip.rs
  stackslib/src/net/api/tests/mod.rs
  stackslib/src/net/api/tests/postblock_proposal.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/server.rs
  stackslib/src/net/stackerdb/sync.rs
  testnet/stacks-node/Cargo.toml
  testnet/stacks-node/src/config.rs
  testnet/stacks-node/src/event_dispatcher.rs
  testnet/stacks-node/src/nakamoto_node/miner.rs
  testnet/stacks-node/src/nakamoto_node/relayer.rs
  testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
  testnet/stacks-node/src/tests/signer/mod.rs
  testnet/stacks-node/src/tests/signer/v0.rs
  testnet/stacks-node/src/tests/signer/v1.rs
Labels: 3.0-must

#5185 Fix unhandled result in block state machine move_to calls
  stacks-signer/src/signerdb.rs
Labels: 3.0-must

#5188 fix: add missing prometheus timers to stacks_client
  stacks-signer/src/client/stacks_client.rs
Labels: 3.0-must

#5179 chore: add debug logs before all `stacks_node_client` use
  stacks-signer/src/client/stacks_client.rs
Labels: 3.0-must

#5161 feat: use `timeout` param from burnchain config
  testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
  testnet/stacks-node/src/config.rs
  testnet/stacks-node/src/tests/signer/v0.rs
Labels: 3.0-must

#5158 fix: disregard tx count if the stacks tip has changed
  testnet/stacks-node/src/neon_node.rs
Labels: 3.0-must

#5191 Fix: 5159, 5169, 5171, 5172, and others
  .github/workflows/bitcoin-tests.yml
  .github/workflows/ci.yml
  .github/workflows/p2p-tests.yml
  .github/workflows/standalone-tests.yml
  Cargo.lock
  stackslib/Cargo.toml
  stackslib/src/chainstate/nakamoto/coordinator/mod.rs
  stackslib/src/net/api/getneighbors.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/connection.rs
  stackslib/src/net/db.rs
  stackslib/src/net/neighbors/db.rs
  stackslib/src/net/neighbors/mod.rs
  stackslib/src/net/neighbors/walk.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/prune.rs
  stackslib/src/net/relay.rs
  stackslib/src/net/stackerdb/mod.rs
  stackslib/src/net/stackerdb/sync.rs
  stackslib/src/net/tests/convergence.rs
  stackslib/src/net/tests/download/nakamoto.rs
  stackslib/src/net/tests/mod.rs
  stackslib/src/net/tests/neighbors.rs
  testnet/stacks-node/src/config.rs
Labels: 3.0-must

#5113 feat: add `block_time` to `/new_block` event payload
  stackslib/src/chainstate/coordinator/mod.rs
  stackslib/src/chainstate/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/stacks/db/blocks.rs
  stackslib/src/net/mod.rs
  testnet/stacks-node/src/event_dispatcher.rs
  testnet/stacks-node/src/run_loop/mod.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
Labels: 3.0-must

#5104 fix: use permanent backoff when stacker set not found
  stacks-signer/src/client/stacks_client.rs
  testnet/stacks-node/src/tests/signer/v0.rs
Labels: 3.0-must

#5196 fix: use lower-cardinality prometheus metrics in signer
  stacks-signer/src/client/stacks_client.rs
Labels: 3.0-must

#5201 fix: limit number of UTXOs retrieved with `listunspent`
  .github/workflows/bitcoin-tests.yml
  testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
  testnet/stacks-node/src/config.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
  testnet/stacks-node/src/tests/signer/v0.rs
Labels: 3.0-must

#5165 chore: avoid warning from duplicate block-commit
  stackslib/src/net/httpcore.rs
  testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
  testnet/stacks-node/src/burnchains/mocknet_controller.rs
  testnet/stacks-node/src/burnchains/mod.rs
  testnet/stacks-node/src/nakamoto_node.rs
  testnet/stacks-node/src/nakamoto_node/relayer.rs
  testnet/stacks-node/src/neon_node.rs
  testnet/stacks-node/src/run_loop/neon.rs
  testnet/stacks-node/src/tests/epoch_205.rs
  testnet/stacks-node/src/tests/epoch_21.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
Labels: 3.0-must

#5206 Fix/5205
  stackslib/src/net/p2p.rs
  testnet/stacks-node/src/nakamoto_node/miner.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
Labels: 3.0-must

#5208 Fix/5203 and 5204
  stackslib/src/net/download/nakamoto/download_state_machine.rs
  stackslib/src/net/download/nakamoto/tenure_downloader.rs
  stackslib/src/net/download/nakamoto/tenure_downloader_set.rs
  stackslib/src/net/tests/download/nakamoto.rs
Labels: 3.0-must

#5207 test: try stopping bitcoind within Rust, rather than spawning the CLI
  .github/workflows/bitcoin-tests.yml
  testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
  testnet/stacks-node/src/tests/bitcoin_regtest.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
Labels: 3.0-must

#5218 Chore: Fix some CI tests
  testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
  testnet/stacks-node/src/tests/signer/mod.rs
  testnet/stacks-node/src/tests/signer/v0.rs
Labels: 3.0-must

#5213 feat: add a consolidated endpoint for current and prior sortitions
  docs/rpc/api/core-node/get_sortitions.example.json
  docs/rpc/api/core-node/get_sortitions_latest_and_prior.example.json
  docs/rpc/openapi.yaml
  stacks-signer/src/chainstate.rs
  stacks-signer/src/client/stacks_client.rs
  stacks-signer/src/tests/chainstate.rs
  stackslib/src/net/api/getsortition.rs
  stackslib/src/net/api/tests/getsortition.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
Labels: 3.0-must

#5154 Add test for flashblocks when epoch 3 is deployed
  .github/workflows/bitcoin-tests.yml
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
Labels: 3.0-must, 3.0-Testing

#5155 Miscellaneous audit fixes
  clarity/src/vm/docs/mod.rs
  contrib/tools/relay-server/src/http.rs
  stacks-common/Cargo.toml
  stacks-signer/src/v0/signer.rs
  stacks-signer/src/v1/signer.rs
  stackslib/src/chainstate/burn/db/sortdb.rs
  stackslib/src/chainstate/nakamoto/miner.rs
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/nakamoto/staging_blocks.rs
  stackslib/src/chainstate/nakamoto/tenure.rs
  stackslib/src/net/api/postblock_proposal.rs
  stackslib/src/net/connection.rs
  stackslib/src/net/mod.rs
  testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
  testnet/stacks-node/src/nakamoto_node/miner.rs
  testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
Labels: 3.0-must

#5223 fix: use `max_unspent_utxos` in `get_all_utxos`
  testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs
Labels: 3.0-must

#5197 Fix/5193 stackerdb decoherence
  stackslib/src/net/api/getneighbors.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/inv/epoch2x.rs
  stackslib/src/net/inv/nakamoto.rs
  stackslib/src/net/neighbors/comms.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/stackerdb/sync.rs
  stackslib/src/net/stackerdb/tests/sync.rs
  stackslib/src/net/tests/httpcore.rs
  testnet/stacks-node/src/tests/signer/mod.rs
Labels: 3.0-must

#5125 feat/monitor-signers CLI command to poll signer stackerdb messages
  libsigner/src/v0/messages.rs
  stacks-signer/src/cli.rs
  stacks-signer/src/client/mod.rs
  stacks-signer/src/client/stacks_client.rs
  stacks-signer/src/lib.rs
  stacks-signer/src/main.rs
  stacks-signer/src/monitor_signers.rs
  stacks-signer/src/runloop.rs
  stacks-signer/src/tests/chainstate.rs
  stacks-signer/src/utils.rs
  testnet/stacks-node/src/neon_node.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
  testnet/stacks-node/src/tests/signer/v1.rs
Labels: 3.0-must

#5221 Fix/5044
  stackslib/src/chainstate/nakamoto/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/nakamoto/tests/node.rs
  stackslib/src/chainstate/stacks/db/accounts.rs
  stackslib/src/net/inv/nakamoto.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/tests/inv/nakamoto.rs
Labels: 3.0-must

#5153 feat: Signer signature count endpoint
  .github/workflows/bitcoin-tests.yml
  CHANGELOG.md
  docs/rpc-endpoints.md
  docs/rpc/openapi.yaml
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/stacks/db/mod.rs
  stackslib/src/net/api/getsigner.rs
  stackslib/src/net/api/mod.rs
  stackslib/src/net/api/tests/getsigner.rs
  stackslib/src/net/api/tests/mod.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
Labels: 3.0-must

#5227 fix: off by one pox set offset
  pox-locking/src/events.rs
  stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
Labels: 3.0-must

#5236 Fix/5230
  .github/workflows/bitcoin-tests.yml
  stackslib/src/chainstate/nakamoto/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/stacks/db/mod.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
Labels: 3.0-must

#5250 Do not leak a private key that has a small typo
  stacks-signer/src/config.rs
Labels: 3.0-must
