Repository stacks-network/stacks-core, pull requests merged in 2024-03, with the labels that each got.

#4460 [CI] Dry x86-64-v3 builds/default images to use glibc
  .github/actions/dockerfiles/Dockerfile.alpine-binary
  .github/actions/dockerfiles/Dockerfile.debian-binary
  .github/actions/dockerfiles/Dockerfile.debian-source
  .github/workflows/create-source-binary-x64.yml
  .github/workflows/create-source-binary.yml
  .github/workflows/github-release.yml
  .github/workflows/image-build-binary.yml
  .github/workflows/image-build-source.yml
  .github/workflows/stacks-core-tests.yml
  Dockerfile.debian
  build-scripts/Dockerfile.linux-glibc-arm64
  build-scripts/Dockerfile.linux-glibc-armv7
  build-scripts/Dockerfile.linux-glibc-x64
  build-scripts/Dockerfile.linux-musl-arm64
  build-scripts/Dockerfile.linux-musl-x64
  build-scripts/Dockerfile.macos-arm64
  build-scripts/Dockerfile.macos-x64
  build-scripts/Dockerfile.windows-x64
  libsigner/Cargo.toml
  libstackerdb/Cargo.toml
  stacks-common/Cargo.toml
  stackslib/Cargo.toml
  stackslib/src/main.rs
  testnet/stacks-node/Cargo.toml
  testnet/stacks-node/src/main.rs
Labels: enhancement, CI, benchmarking

#4497 Move the Creation of Source Binaries to Composite
  .github/workflows/create-source-binary.yml
  build-scripts/Dockerfile.linux-glibc-arm64
  build-scripts/Dockerfile.linux-glibc-armv7
  build-scripts/Dockerfile.linux-glibc-x64
  build-scripts/Dockerfile.linux-musl-arm64
  build-scripts/Dockerfile.linux-musl-armv7
  build-scripts/Dockerfile.linux-musl-x64
  build-scripts/Dockerfile.macos-arm64
  build-scripts/Dockerfile.macos-x64
  build-scripts/Dockerfile.windows-x64
  build-scripts/build-dist.sh
Labels: enhancement, CI

#4563 fix: handle burn chain flapping
  .github/workflows/bitcoin-tests.yml
  stackslib/src/burnchains/bitcoin/indexer.rs
  stackslib/src/burnchains/db.rs
  stackslib/src/chainstate/coordinator/mod.rs
  testnet/stacks-node/src/tests/bitcoin_regtest.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
Labels: 2.5

#4560 Add affirmation overrides config option and add default xenon ones ne…
  stackslib/src/burnchains/db.rs
  testnet/stacks-node/src/config.rs
  testnet/stacks-node/src/run_loop/neon.rs
Labels: 2.5

#4572 Chore/fix clippy nursery warning
  stacks-signer/src/cli.rs
  stacks-signer/src/client/stackerdb.rs
  stacks-signer/src/client/stacks_client.rs
  stacks-signer/src/config.rs
  stacks-signer/src/coordinator.rs
  stacks-signer/src/runloop.rs
  stacks-signer/src/signer.rs
  stacks-signer/src/signerdb.rs
Labels: profiling

#4590 create release only requires a tag
  .github/workflows/ci.yml
  .github/workflows/create-source-binary.yml
  .github/workflows/github-release.yml
  .github/workflows/image-build-binary.yml
Labels: ship now, CI
