Repository stacks-network/stacks-core, pull requests merged in 2024-10, with the labels that each got.

#5254 Fix: /v3/sortitions calculation and tenure extend behavior
  stackslib/src/net/api/getsortition.rs
  testnet/stacks-node/src/nakamoto_node/miner.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
Labels: 3.0-must

#5259 Chore: remove infinite loop in signer during tests
  stacks-signer/src/client/stacks_client.rs
  stacks-signer/src/v0/signer.rs
Labels: 3.0-must

#5237 Fix multiple_miners* tests
  stacks-signer/src/client/mod.rs
  stacks-signer/src/client/stacks_client.rs
  stacks-signer/src/v0/signer.rs
  testnet/stacks-node/src/tests/epoch_25.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
  testnet/stacks-node/src/tests/signer/mod.rs
  testnet/stacks-node/src/tests/signer/v0.rs
Labels: 3.0-must

#5253 Fix/5249
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/nakamoto/staging_blocks.rs
  stackslib/src/main.rs
  stackslib/src/net/api/getblock_v3.rs
  stackslib/src/net/api/getsortition.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/download/nakamoto/tenure_downloader.rs
  stackslib/src/net/httpcore.rs
  stackslib/src/net/inv/nakamoto.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/tests/download/nakamoto.rs
  stackslib/src/net/tests/inv/nakamoto.rs
Labels: 3.0-must

#5270 Fix/5267
  stackslib/src/net/download/nakamoto/download_state_machine.rs
  stackslib/src/net/download/nakamoto/tenure_downloader.rs
  stackslib/src/net/download/nakamoto/tenure_downloader_set.rs
  stackslib/src/net/tests/download/nakamoto.rs
Labels: 3.0-must

#5257 add Nakamoto block heights to info logs for easier integration with log analysis tools
  stacks-signer/src/chainstate.rs
  stacks-signer/src/v0/signer.rs
Labels: signer

#5305 Fix/nakamoto downloader at reward cycle boundary
  stackslib/src/net/download/nakamoto/tenure.rs
  stackslib/src/net/download/nakamoto/tenure_downloader_set.rs
  stackslib/src/net/inv/nakamoto.rs
Labels: 3.0-must

#5300 feat: make `chain_id` configurable
  testnet/stacks-node/conf/local-follower-conf.toml
  testnet/stacks-node/conf/mainnet-follower-conf.toml
  testnet/stacks-node/conf/mocknet-follower-conf.toml
  testnet/stacks-node/conf/regtest-follower-conf.toml
  testnet/stacks-node/conf/testnet-follower-conf.toml
  testnet/stacks-node/src/config.rs
  testnet/stacks-node/src/tests/epoch_205.rs
  testnet/stacks-node/src/tests/epoch_21.rs
  testnet/stacks-node/src/tests/epoch_22.rs
  testnet/stacks-node/src/tests/epoch_23.rs
  testnet/stacks-node/src/tests/epoch_24.rs
  testnet/stacks-node/src/tests/epoch_25.rs
  testnet/stacks-node/src/tests/integrations.rs
  testnet/stacks-node/src/tests/mempool.rs
  testnet/stacks-node/src/tests/mod.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
  testnet/stacks-node/src/tests/signer/v0.rs
  testnet/stacks-node/src/tests/stackerdb.rs
Labels: 3.0-must

#5302 Fix/stackerdb sync for 3.0-rc3
  stackslib/src/net/p2p.rs
  stackslib/src/net/stackerdb/mod.rs
  stackslib/src/net/stackerdb/sync.rs
  stackslib/src/net/stackerdb/tests/sync.rs
Labels: 3.0-must

#5291 fix: use O(n) instead of mn when checking pox bitvec
  stackslib/src/chainstate/nakamoto/mod.rs
Labels: 3.0-must

#5294 Do not error if block submit fails in mock mining case in Nakamoto
  testnet/stacks-node/src/nakamoto_node/relayer.rs
Labels: 3.0-must

#5289 feat: support re-sending events to event observers across restarts
  CHANGELOG.md
  Cargo.lock
  testnet/stacks-node/Cargo.toml
  testnet/stacks-node/src/config.rs
  testnet/stacks-node/src/event_dispatcher.rs
  testnet/stacks-node/src/node.rs
  testnet/stacks-node/src/run_loop/nakamoto.rs
  testnet/stacks-node/src/run_loop/neon.rs
Labels: 3.0-must

#5308 feat: Add tenure-height to the /v2/info endpoint
  CHANGELOG.md
  docs/rpc/api/core-node/get-info.example.json
  docs/rpc/api/core-node/get-info.schema.json
  stacks-signer/src/client/mod.rs
  stackslib/src/net/api/getinfo.rs
  stackslib/src/net/api/postmempoolquery.rs
  stackslib/src/net/api/tests/getinfo.rs
  stackslib/src/net/api/tests/gettenureinfo.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/tests/relay/nakamoto.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
Labels: 3.0-must

#5336 Add version to signer messages
  libsigner/src/libsigner.rs
  libsigner/src/v0/messages.rs
  stacks-signer/src/cli.rs
  stacks-signer/src/client/stackerdb.rs
  stacks-signer/src/lib.rs
  stacks-signer/src/main.rs
  stacks-signer/src/monitoring/server.rs
  stacks-signer/src/v0/signer.rs
  testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs
  testnet/stacks-node/src/tests/signer/mod.rs
  testnet/stacks-node/src/tests/signer/v0.rs
Labels: 3.0-Signer
