Repository stacks-network/stacks-core, pull requests merged in 2025-04, with the labels that each got.

#5976 Update ci workflow
  .github/workflows/ci.yml
  .github/workflows/github-release.yml
Labels: CI

#5990 chore: A few workflow fixes
  .github/workflows/github-release.yml
  .github/workflows/image-build-source.yml
  contrib/tools/block-replay.sh
Labels: chore, CI

#5995 Resolves issues 5991 and 5989
  .github/workflows/clippy.yml
  .github/workflows/github-release.yml
Labels: CI

#5982 chore: add http traffic heartbeat log
  stackslib/src/net/httpcore.rs
Labels: chore

#6044 Perf: faster readonly MARF
  stackslib/src/chainstate/burn/db/sortdb.rs
  stackslib/src/chainstate/stacks/index/marf.rs
  stackslib/src/chainstate/stacks/index/storage.rs
  stackslib/src/clarity_vm/database/marf.rs
  stackslib/src/util_lib/db.rs
Labels: performance-optimizations

#6038 Perf: descendancy check
  stackslib/src/chainstate/burn/db/sortdb.rs
Labels: performance-optimizations

#6050 Perf: Check and create metadata index in ClarityDB
  clarity/src/vm/database/sqlite.rs
  stackslib/src/clarity_vm/clarity.rs
Labels: performance-optimizations
