Repository stacks-network/stacks-core, pull requests merged in 2025-01, with the labels that each got.

#5630 Fix collapsible_else_if clippy warnings in stackslib
  stackslib/src/burnchains/bitcoin/address.rs
  stackslib/src/burnchains/bitcoin/indexer.rs
  stackslib/src/burnchains/bitcoin/spv.rs
  stackslib/src/burnchains/tests/affirmation.rs
  stackslib/src/chainstate/burn/db/sortdb.rs
  stackslib/src/chainstate/burn/operations/leader_block_commit.rs
  stackslib/src/chainstate/coordinator/mod.rs
  stackslib/src/chainstate/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/miner.rs
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/nakamoto/staging_blocks.rs
  stackslib/src/chainstate/nakamoto/tests/node.rs
  stackslib/src/chainstate/stacks/auth.rs
  stackslib/src/chainstate/stacks/db/blocks.rs
  stackslib/src/chainstate/stacks/index/mod.rs
  stackslib/src/chainstate/stacks/index/proofs.rs
  stackslib/src/chainstate/stacks/index/storage.rs
  stackslib/src/chainstate/stacks/tests/accounting.rs
  stackslib/src/chainstate/stacks/transaction.rs
  stackslib/src/net/atlas/db.rs
  stackslib/src/net/atlas/download.rs
  stackslib/src/net/connection.rs
  stackslib/src/net/download/epoch2x.rs
  stackslib/src/net/inv/epoch2x.rs
  stackslib/src/net/mempool/mod.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/neighbors/rpc.rs
  stackslib/src/net/stackerdb/db.rs
  stackslib/src/net/tests/download/epoch2x.rs
Labels: lint

#5645 Fix clippy::redundant_closure throughout stackslib
  stackslib/src/blockstack_cli.rs
  stackslib/src/burnchains/db.rs
  stackslib/src/burnchains/tests/affirmation.rs
  stackslib/src/chainstate/burn/db/sortdb.rs
  stackslib/src/chainstate/burn/operations/delegate_stx.rs
  stackslib/src/chainstate/burn/operations/stack_stx.rs
  stackslib/src/chainstate/burn/operations/transfer_stx.rs
  stackslib/src/chainstate/burn/operations/vote_for_aggregate_key.rs
  stackslib/src/chainstate/coordinator/mod.rs
  stackslib/src/chainstate/nakamoto/signer_set.rs
  stackslib/src/chainstate/nakamoto/tenure.rs
  stackslib/src/chainstate/nakamoto/tests/mod.rs
  stackslib/src/chainstate/stacks/boot/mod.rs
  stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
  stackslib/src/chainstate/stacks/db/accounts.rs
  stackslib/src/chainstate/stacks/db/blocks.rs
  stackslib/src/chainstate/stacks/db/mod.rs
  stackslib/src/chainstate/stacks/index/storage.rs
  stackslib/src/chainstate/stacks/index/test/marf.rs
  stackslib/src/clarity_cli.rs
  stackslib/src/clarity_vm/database/mod.rs
  stackslib/src/core/mempool.rs
  stackslib/src/net/api/getpoxinfo.rs
  stackslib/src/net/api/tests/mod.rs
  stackslib/src/net/atlas/db.rs
  stackslib/src/net/atlas/download.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/db.rs
  stackslib/src/net/neighbors/comms.rs
  stackslib/src/net/relay.rs
  stackslib/src/net/stackerdb/db.rs
  stackslib/src/net/tests/mempool/mod.rs
  stackslib/src/util_lib/db.rs
Labels: lint

#5700 Fix clippy::useless_conversions throughout stacks core
  stackslib/src/burnchains/bitcoin/bits.rs
  stackslib/src/burnchains/mod.rs
  stackslib/src/burnchains/tests/db.rs
  stackslib/src/chainstate/coordinator/mod.rs
  stackslib/src/chainstate/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/nakamoto/shadow.rs
  stackslib/src/chainstate/nakamoto/tests/node.rs
  stackslib/src/chainstate/stacks/boot/contract_tests.rs
  stackslib/src/chainstate/stacks/boot/mod.rs
  stackslib/src/chainstate/stacks/boot/pox_2_tests.rs
  stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
  stackslib/src/chainstate/stacks/db/blocks.rs
  stackslib/src/chainstate/stacks/index/storage.rs
  stackslib/src/chainstate/stacks/tests/mod.rs
  stackslib/src/clarity_vm/clarity.rs
  stackslib/src/clarity_vm/database/mod.rs
  stackslib/src/core/tests/mod.rs
  stackslib/src/net/api/getpoxinfo.rs
  stackslib/src/net/codec.rs
  stackslib/src/net/download/nakamoto/download_state_machine.rs
  stackslib/src/net/download/nakamoto/tenure_downloader_unconfirmed.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/stackerdb/config.rs
  stackslib/src/net/tests/download/epoch2x.rs
  stackslib/src/net/tests/download/nakamoto.rs
  stackslib/src/net/tests/mod.rs
  stackslib/src/net/tests/relay/epoch2x.rs
Labels: lint

#5702 Fix clippy::unnecessary_operation throughout stacks core
  stackslib/src/chainstate/stacks/boot/contract_tests.rs
Labels: lint

#5693 Fix clippy::needless_borrowed_ref throughout
  stackslib/src/chainstate/stacks/transaction.rs
  stackslib/src/net/prune.rs
Labels: lint

#5695 Fix clippy::unnecessary_lazy_evaluations throughout stacks core
  stackslib/src/chainstate/stacks/db/accounts.rs
  stackslib/src/chainstate/stacks/db/mod.rs
  stackslib/src/chainstate/stacks/miner.rs
  stackslib/src/cost_estimates/pessimistic.rs
  stackslib/src/monitoring/mod.rs
Labels: lint

#5698 Fix clippy::unnecessary_mut_passed throughout
  stackslib/src/burnchains/tests/mod.rs
  stackslib/src/chainstate/burn/db/sortdb.rs
  stackslib/src/chainstate/coordinator/mod.rs
  stackslib/src/chainstate/stacks/db/mod.rs
  stackslib/src/chainstate/stacks/tests/chain_histories.rs
  stackslib/src/chainstate/stacks/transaction.rs
  stackslib/src/clarity_cli.rs
  stackslib/src/clarity_vm/tests/events.rs
  stackslib/src/clarity_vm/tests/forking.rs
  stackslib/src/clarity_vm/tests/large_contract.rs
  stackslib/src/cli.rs
  stackslib/src/core/tests/mod.rs
  stackslib/src/net/api/postblock_proposal.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/download/nakamoto/download_state_machine.rs
  stackslib/src/net/httpcore.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/tests/download/epoch2x.rs
  stackslib/src/net/tests/neighbors.rs
  stackslib/src/net/tests/relay/nakamoto.rs
Labels: lint

#5696 Fix clippy::unnecessary_literal_unwrap throughout stacks core
  stackslib/src/chainstate/stacks/index/test/marf.rs
Labels: lint

#5694 Fix clippy::unnecessary_fold throughout stacks core
  stackslib/src/chainstate/burn/operations/leader_block_commit.rs
  stackslib/src/net/relay.rs
Labels: lint

#5697 chore: Apply Clippy lint `needless_collect`
  stackslib/src/net/tests/inv/nakamoto.rs
  stackslib/src/net/tests/mempool/mod.rs
  testnet/stacks-node/src/neon_node.rs
  testnet/stacks-node/src/tests/integrations.rs
  testnet/stacks-node/src/tests/mod.rs
  testnet/stacks-node/src/tests/signer/v0.rs
Labels: lint

#5699 chore: Apply Clippy `set_contains_or_insert`
  testnet/stacks-node/src/neon_node.rs
Labels: lint

#5734 Chore/add clippy-stacks alias
  .cargo/config.toml
  .github/workflows/clippy.yml
  CONTRIBUTING.md
  clarity/src/vm/ast/parser/v2/mod.rs
Labels: lint

#5656 chore: Apply Clippy `vec_init_then_push`, `map_clone`, `map_entry`, and `iter_*` lints
  clarity/src/vm/tests/datamaps.rs
  stacks-common/src/address/c32_old.rs
  stacks-common/src/util/chunked_encoding.rs
  stackslib/src/burnchains/affirmation.rs
  stackslib/src/burnchains/burnchain.rs
  stackslib/src/burnchains/db.rs
  stackslib/src/chainstate/nakamoto/coordinator/tests.rs
  stackslib/src/chainstate/stacks/db/unconfirmed.rs
  stackslib/src/chainstate/stacks/index/cache.rs
  stackslib/src/chainstate/stacks/miner.rs
  stackslib/src/chainstate/stacks/tests/chain_histories.rs
  stackslib/src/clarity_cli.rs
  stackslib/src/core/mempool.rs
  stackslib/src/net/api/tests/getheaders.rs
  stackslib/src/net/api/tests/postblock_v3.rs
  stackslib/src/net/api/tests/postmempoolquery.rs
  stackslib/src/net/atlas/download.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/connection.rs
  stackslib/src/net/db.rs
  stackslib/src/net/download/nakamoto/download_state_machine.rs
  stackslib/src/net/http/request.rs
  stackslib/src/net/http/response.rs
  stackslib/src/net/inv/nakamoto.rs
  stackslib/src/net/mod.rs
  stackslib/src/net/neighbors/comms.rs
  stackslib/src/net/neighbors/db.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/relay.rs
  stackslib/src/net/server.rs
  stackslib/src/net/tests/download/epoch2x.rs
  stackslib/src/net/tests/inv/nakamoto.rs
  stackslib/src/net/tests/mempool/mod.rs
Labels: lint

#5744 chore: Apply Clippy lint `match_like_matches_macro`
  stackslib/src/burnchains/bitcoin/address.rs
  stackslib/src/burnchains/mod.rs
  stackslib/src/chainstate/burn/operations/delegate_stx.rs
  stackslib/src/chainstate/burn/operations/leader_block_commit.rs
  stackslib/src/chainstate/stacks/auth.rs
  stackslib/src/chainstate/stacks/index/node.rs
  stackslib/src/chainstate/stacks/miner.rs
  stackslib/src/chainstate/stacks/mod.rs
  stackslib/src/chainstate/stacks/tests/block_construction.rs
  stackslib/src/chainstate/stacks/transaction.rs
  stackslib/src/clarity_cli.rs
  stackslib/src/net/atlas/download.rs
  stackslib/src/net/codec.rs
  stackslib/src/net/http/common.rs
  stackslib/src/net/tests/inv/nakamoto.rs
Labels: lint

#5748 chore: Apply Clippy lint `manual_inspect`
  stackslib/src/burnchains/bitcoin/address.rs
  stackslib/src/burnchains/bitcoin/bits.rs
  stackslib/src/burnchains/bitcoin/indexer.rs
  stackslib/src/burnchains/bitcoin/spv.rs
  stackslib/src/burnchains/burnchain.rs
  stackslib/src/chainstate/burn/db/sortdb.rs
  stackslib/src/chainstate/burn/operations/leader_block_commit.rs
  stackslib/src/chainstate/nakamoto/mod.rs
  stackslib/src/chainstate/nakamoto/shadow.rs
  stackslib/src/chainstate/stacks/db/blocks.rs
  stackslib/src/chainstate/stacks/index/marf.rs
  stackslib/src/chainstate/stacks/index/storage.rs
  stackslib/src/chainstate/stacks/index/trie.rs
  stackslib/src/chainstate/stacks/tests/mod.rs
  stackslib/src/config/mod.rs
  stackslib/src/net/asn.rs
  stackslib/src/net/chat.rs
  stackslib/src/net/download/nakamoto/download_state_machine.rs
  stackslib/src/net/download/nakamoto/tenure_downloader.rs
  stackslib/src/net/download/nakamoto/tenure_downloader_set.rs
  stackslib/src/net/httpcore.rs
  stackslib/src/net/inv/epoch2x.rs
  stackslib/src/net/inv/nakamoto.rs
  stackslib/src/net/neighbors/comms.rs
  stackslib/src/net/neighbors/db.rs
  stackslib/src/net/p2p.rs
  stackslib/src/net/relay.rs
Labels: lint

#5633 chore(stacks-common): Remove unused imports and enable warning
  stacks-common/src/address/b58.rs
  stacks-common/src/address/mod.rs
  stacks-common/src/bitvec.rs
  stacks-common/src/deps_common/bitcoin/blockdata/block.rs
  stacks-common/src/deps_common/bitcoin/blockdata/script.rs
  stacks-common/src/deps_common/bitcoin/blockdata/transaction.rs
  stacks-common/src/deps_common/bitcoin/network/message_network.rs
  stacks-common/src/deps_common/bitcoin/util/hash.rs
  stacks-common/src/deps_common/httparse/mod.rs
  stacks-common/src/libcommon.rs
  stacks-common/src/types/chainstate.rs
  stacks-common/src/types/mod.rs
  stacks-common/src/util/chunked_encoding.rs
  stacks-common/src/util/db.rs
  stacks-common/src/util/hash.rs
  stacks-common/src/util/log.rs
  stacks-common/src/util/mod.rs
  stacks-common/src/util/pipe.rs
  stacks-common/src/util/retry.rs
  stacks-common/src/util/secp256k1.rs
  stacks-common/src/util/vrf.rs
  stackslib/src/blockstack_cli.rs
Labels: lint

#5654 chore: Apply Clippy lint `collection_is_never_used`
  stackslib/src/burnchains/tests/burnchain.rs
  stackslib/src/burnchains/tests/db.rs
  stackslib/src/chainstate/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/coordinator/tests.rs
  stackslib/src/chainstate/nakamoto/tests/mod.rs
  stackslib/src/chainstate/stacks/block.rs
  stackslib/src/chainstate/stacks/boot/pox_4_tests.rs
  stackslib/src/chainstate/stacks/db/transactions.rs
  stackslib/src/chainstate/stacks/index/test/trie.rs
  stackslib/src/chainstate/stacks/tests/block_construction.rs
  stackslib/src/chainstate/stacks/tests/chain_histories.rs
  stackslib/src/chainstate/stacks/tests/mod.rs
  stackslib/src/chainstate/stacks/transaction.rs
  stackslib/src/core/tests/mod.rs
  stackslib/src/net/atlas/tests.rs
  stackslib/src/net/tests/download/epoch2x.rs
  stackslib/src/net/tests/mempool/mod.rs
  stackslib/src/net/tests/mod.rs
  stackslib/src/net/tests/relay/nakamoto.rs
  stackslib/src/util_lib/strings.rs
  testnet/stacks-node/src/event_dispatcher.rs
  testnet/stacks-node/src/tests/epoch_21.rs
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
  testnet/stacks-node/src/tests/neon_integrations.rs
Labels: lint

#5785 fix: Disable flaky test `flash_blocks_on_epoch_3`
  .github/workflows/bitcoin-tests.yml
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
Labels: flaky

#5784 Test: Refactor block waits
  testnet/stacks-node/src/tests/nakamoto_integrations.rs
  testnet/stacks-node/src/tests/signer/mod.rs
  testnet/stacks-node/src/tests/signer/v0.rs
Labels: refactoring, testing, flaky
